use 50_Days_SQL_Challenge;


--=========================================================================================
-- DAY 48 TASKS

-- 1. Find total business revenue.

--=========================================================================================


SELECT 
    SUM(payment_amount) AS total_revenue
FROM 
    cleaned_payments;


--=========================================================================================

-- 2. Find daily revenue.

--=========================================================================================

SELECT 
    payment_date,
    SUM(payment_amount) AS total_revenue
FROM 
    cleaned_payments
GROUP BY 1
ORDER BY 2 DESC;

--=========================================================================================

-- 3. Find monthly revenue trend.

--=========================================================================================


SELECT 
    TO_CHAR(payment_date,'Month') AS month,
    SUM(payment_amount) AS total_revenue
FROM 
    cleaned_payments
GROUP BY 1
ORDER BY 2 DESC;



--=========================================================================================

-- 4. Find revenue generated by each product.

--=========================================================================================


SELECT 
    p.product_name,
    SUM(pa.payment_amount) AS revenue_by_each_product
FROM 
    cleaned_payments pa
JOIN 
    cleaned_order_details o 
ON 
    pa.order_id = o.order_id
JOIN 
    cleaned_products p  
ON 
    o.product_id = p.product_id 
GROUP BY 1
ORDER BY 2 DESC
;

--=========================================================================================

-- 5. Find customer-wise revenue.

--=========================================================================================



SELECT 
    c.customer_name,
    SUM(pa.payment_amount) AS revenue_by_each_customer
FROM 
    cleaned_payments pa
JOIN 
    cleaned_orders o 
ON 
    pa.order_id = o.order_id
JOIN 
    cleaned_customers c  
ON 
    o.customer_id = c.customer_id 
GROUP BY 1
ORDER BY 2 DESC
;

--=========================================================================================

-- 6. Find category-wise revenue.

--=========================================================================================

SELECT 
    p.category,
    SUM(pa.payment_amount) AS revenue_by_each_product
FROM 
    cleaned_payments pa
JOIN 
    cleaned_order_details o 
ON 
    pa.order_id = o.order_id
JOIN 
    cleaned_products p  
ON 
    o.product_id = p.product_id 
GROUP BY 1
ORDER BY 2 DESC
;


--=========================================================================================

-- 7. Find days generating highest revenue.

--=========================================================================================


SELECT 
    TO_CHAR(payment_date,'Day') AS day_of_the_week,
    SUM(payment_amount) AS total_revenue
FROM 
    cleaned_payments
GROUP BY 1
ORDER BY 2 DESC;

--=========================================================================================

-- OR

--=========================================================================================

SELECT 
    TO_CHAR(payment_date,'Day') AS day_of_the_week,
    SUM(payment_amount) AS total_revenue
FROM 
    cleaned_payments
GROUP BY 1
ORDER BY 2 DESC;
